# -*- coding: utf-8 -*-
"""BAN3110 Week 4 Module 4 HW4 Omy Ortiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NacKvygK2NpaY2QATIs3lMuvrbTh5EN2

**BAN3110** Module 4 Homework 4
#####**Name:** Omy Ortiz
#####**AI Use Statement:** I used ChatGPT to explain my method and approach, help with Google Colab, and get help with Python syntax.  I typed, ran, and checked all of the code.

##### **Problem 1**: Write a program that considers given list and prints True if all of them are odd, and False otherwise.
"""

L = [2, 1, 3, 5, 7, 9, 4]

all_odd = True

for number in L:
    if number % 2 == 0:
        all_odd = False
        break

print(all_odd)

"""##### **Problem 2**: Write a Python code which finds the smallest even and odd numbers in a given list."""

L = [3, 6, 7, 9, 11, 15, 18, 66, 77, 365, 468, 5]

even_list = []
odd_list = []

for num in L:
    if num % 2 == 0:
        even_list.append(num)
    else:
        odd_list.append(num)

even_list.sort()
odd_list.sort()

smallest_even = even_list[0]
smallest_odd = odd_list[0]

print("Smallest Even:", smallest_even)
print("Smallest Odd:", smallest_odd)

"""##### **Problem 3**: Write a Python code which finds common even values between given two lists A and B by using for loop and if statement? If the lists are given as follows, list1=[10,66,45,13,18,8] list2=[8,17,5,66,18,22, 6,548], then the common even values are 8,66, and 18."""

list1 = [10, 66, 45, 13, 18, 8, 4, 88]
list2 = [8, 17, 5, 66, 18, 22, 6, 548, 4, 88]

common_even_numbers = []

for num in list1:
  if num % 2 == 0 and num in list2:
    common_even_numbers.append(num)

print("Common Even Numbers:", common_even_numbers)

"""##### **Problem 4**: How to get the nth smallest even value of given array?"""

list = [11,23,58,31,56,22,43,12,65,19,6,7,4,5]
n = 4

even_list = []

for num in list:
  if num % 2 == 0:
    even_list.append(num)

even_list.sort()

nth_smallest_even = even_list[n]

print("Nth smallest even value:", nth_smallest_even)